AFSOEC/AFSOEC/Controllers/AFSTreatmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AFSOEC.Models;
using Microsoft.AspNetCore.Http;

namespace AFSOEC.Controllers
{
    public class AFSTreatmentController : Controller
    {
        private readonly OECContext _context;

        public AFSTreatmentController(OECContext context)
        {
            _context = context;
        }

        // GET: AFSTreatment
        public async Task<IActionResult> Index(int PlotId, int FarmId)
        {
            int CurrentPlotId =PlotId;
           // int CurrentFarmId;


            //if (PlotId!=0)
            //{
            //    CurrentPlotId = PlotId;
            //}
            //else
            //{
            //    CurrentPlotId =(int) HttpContext.Session.GetInt32("CurrentPlotId");
            //}

            if (CurrentPlotId == 0)
            {
                CurrentPlotId =(int) HttpContext.Session.GetInt32("CurrentPlotId");
            }

            HttpContext.Session.SetInt32(nameof(CurrentPlotId), CurrentPlotId);

            var farmId = _context.Treatment
                        .Include(t => t.Plot)
                        .Where(t => t.Plot.PlotId == CurrentPlotId)
                        .Select(t => t.Plot.FarmId)
                        .FirstOrDefault();
            HttpContext.Session.SetInt32(nameof(FarmId), FarmId);
            //if (FarmId!=0)
            //{
            //    CurrentFarmId = FarmId;
            //}
            //else
            //{
            //    CurrentFarmId = (int)HttpContext.Session.GetInt32("FarmId");
            //}

            //var FarmName = _context.Plot
            //             .Include(p => p.Farm)
            //             .Where(p => p.FarmId == FarmId)
            //             .Select(p => p.Farm.Name)
            //             .FirstOrDefault();
            var FarmName = _context.Treatment
                            .Include(p => p.Plot.Farm)
                            .Where(p => p.Plot.FarmId == farmId)
                            .Select(p => p.Plot.Farm.Name)
                            .FirstOrDefault();


           HttpContext.Session.SetString(nameof(FarmName), FarmName);
           ViewBag.FarmName = HttpContext.Session.GetString("FarmName");

            var oECContext = _context.Treatment
                            .Include(t => t.Plot)
                            .Where(t => t.PlotId == CurrentPlotId)
                            .Include(t=>t.TreatmentFertilizer);

            //var TreatmentId = _context.Treatment.Include(t => t.TreatmentFertilizer).Where(t => t.PlotId == PlotId);
            //var TraetmentName = _context.TreatmentFertilizer
            //                    .Include(tf => tf.FertilizerName)
            //                    .Where(tf => tf.TreatmentId == int.Parse(TreatmentId.ToString()));
           
            return View(await oECContext.ToListAsync());
        }

        // GET: AFSTreatment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.FarmName = HttpContext.Session.GetString("FarmName");

            if (id == null)
            {
                return NotFound();
            }

            var treatment = await _context.Treatment
                .Include(t => t.Plot)
                .FirstOrDefaultAsync(m => m.TreatmentId == id);
            if (treatment == null)
            {
                return NotFound();
            }

            return View(treatment);
        }

        // GET: AFSTreatment/Create
        public IActionResult Create()
        {
            ViewBag.FarmName = HttpContext.Session.GetString("FarmName");

            int PlotId =(int) HttpContext.Session.GetInt32("CurrentPlotId");
            HttpContext.Session.SetInt32(nameof(PlotId), PlotId);


            ViewData["PlotId"] = new SelectList(_context.Plot.Where(p=>p.PlotId==PlotId), "PlotId", "PlotId");
            return View();
        }

        // POST: AFSTreatment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TreatmentId,Name,PlotId,Moisture,Yield,Weight")] Treatment treatment)
        {
            Treatment thisTreatment = treatment;
        
            int PlotId = thisTreatment.PlotId;
            //var FarmId = _context.Treatment
            //            .Include(t => t.Plot)
            //            .Where(t => t.Plot.PlotId == thisTreatment.PlotId)
            //            .Select(t => t.Plot.FarmId)
            //            .FirstOrDefault();

            //var FarmName = _context.Treatment
            //                .Include(p => p.Plot.Farm)
            //                .Where(p => p.Plot.FarmId == FarmId)
            //                .Select(p => p.Plot.Farm.Name)
            //                .FirstOrDefault();

            HttpContext.Session.SetInt32(nameof(PlotId), PlotId);
           // HttpContext.Session.SetString(nameof(FarmName), FarmName);
            ViewBag.FarmName = HttpContext.Session.GetString("FarmName");

            if (ModelState.IsValid)
            {
                _context.Add(treatment);
                TempData["Message"] = "Treatment for " + HttpContext.Session.GetString("FarmName") + " is created successfully";

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlotId"] = new SelectList(_context.Plot, "PlotId", "PlotId", treatment.PlotId);
            return View(treatment);
        }

        // GET: AFSTreatment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //ViewBag.FarmName = HttpContext.Session.GetString("FarmName");
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await _context.Treatment.FindAsync(id);
            if (treatment == null)
            {
                return NotFound();
            }
            ViewData["PlotId"] = new SelectList(_context.Plot, "PlotId", "PlotId", treatment.PlotId);
            return View(treatment);
        }

        // POST: AFSTreatment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TreatmentId,Name,PlotId,Moisture,Yield,Weight")] Treatment treatment)
        {
            string currentFarmName = HttpContext.Session.GetString("FarmName");
            ViewBag.FarmName = currentFarmName;
            if (id != treatment.TreatmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treatment);
                    TempData["Message"] = $"Treatment for farm {currentFarmName} Updated successfully";

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreatmentExists(treatment.TreatmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlotId"] = new SelectList(_context.Plot, "PlotId", "PlotId", treatment.PlotId);
            return View(treatment);
        }

        // GET: AFSTreatment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.FarmName = HttpContext.Session.GetString("FarmName");
            if (id == null)
            {
                return NotFound();
            }

            var treatment = await _context.Treatment
                .Include(t => t.Plot)
                .FirstOrDefaultAsync(m => m.TreatmentId == id);
            if (treatment == null)
            {
                return NotFound();
            }

            return View(treatment);
        }

        // POST: AFSTreatment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           string currentFarmName = HttpContext.Session.GetString("FarmName");
            var treatment = await _context.Treatment.FindAsync(id);
            _context.Treatment.Remove(treatment);
            TempData["Message"] = $"Trearment for farm {currentFarmName} is deleted successfully";
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TreatmentExists(int id)
        {
            return _context.Treatment.Any(e => e.TreatmentId == id);
        }
    }
}

AFSOEC/AFSOEC/Views/AFSPlot/Create.cshtml
@model AFSOEC.Models.Plot

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Plot</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FarmId" class="control-label">Farm Name</label>
                <select asp-for="FarmId" class ="form-control" asp-items="ViewBag.FarmId"></select>
            </div>
            <div class="form-group">
                <label asp-for="VarietyId" class="control-label">Variety Name</label>
                <select asp-for="VarietyId" class ="form-control" asp-items="ViewBag.VarietyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DatePlanted" class="control-label"></label>
                <input asp-for="DatePlanted" class="form-control" />
                <span asp-validation-for="DatePlanted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateHarvested" class="control-label"></label>
                <input asp-for="DateHarvested" class="form-control" />
                <span asp-validation-for="DateHarvested" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlantingRate" class="control-label"></label>
                <input asp-for="PlantingRate" class="form-control" />
                <span asp-validation-for="PlantingRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="PlantingRateByPounds" /> @Html.DisplayNameFor(model => model.PlantingRateByPounds)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="RowWidth" class="control-label"></label>
                <input asp-for="RowWidth" class="form-control" />
                <span asp-validation-for="RowWidth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PatternRepeats" class="control-label"></label>
                <input asp-for="PatternRepeats" class="form-control" />
                <span asp-validation-for="PatternRepeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrganicMatter" class="control-label"></label>
                <input asp-for="OrganicMatter" class="form-control" />
                <span asp-validation-for="OrganicMatter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BicarbP" class="control-label"></label>
                <input asp-for="BicarbP" class="form-control" />
                <span asp-validation-for="BicarbP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Potassium" class="control-label"></label>
                <input asp-for="Potassium" class="form-control" />
                <span asp-validation-for="Potassium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Magnesium" class="control-label"></label>
                <input asp-for="Magnesium" class="form-control" />
                <span asp-validation-for="Magnesium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calcium" class="control-label"></label>
                <input asp-for="Calcium" class="form-control" />
                <span asp-validation-for="Calcium" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PHsoil" class="control-label"></label>
                <input asp-for="PHsoil" class="form-control" />
                <span asp-validation-for="PHsoil" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PHbuffer" class="control-label"></label>
                <input asp-for="PHbuffer" class="form-control" />
                <span asp-validation-for="PHbuffer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cec" class="control-label"></label>
                <input asp-for="Cec" class="form-control" />
                <span asp-validation-for="Cec" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PercentBaseSaturationK" class="control-label"></label>
                <input asp-for="PercentBaseSaturationK" class="form-control" />
                <span asp-validation-for="PercentBaseSaturationK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PercentBaseSaturationMg" class="control-label"></label>
                <input asp-for="PercentBaseSaturationMg" class="form-control" />
                <span asp-validation-for="PercentBaseSaturationMg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PercentBaseSaturationCa" class="control-label"></label>
                <input asp-for="PercentBaseSaturationCa" class="form-control" />
                <span asp-validation-for="PercentBaseSaturationCa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PercentBaseSaturationH" class="control-label"></label>
                <input asp-for="PercentBaseSaturationH" class="form-control" />
                <span asp-validation-for="PercentBaseSaturationH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AFSOEC/AFSOEC/Views/AFSPlot/Delete.cshtml
@model AFSOEC.Models.Plot

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Plot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatePlanted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePlanted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateHarvested)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateHarvested)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantingRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantingRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantingRateByPounds)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantingRateByPounds)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RowWidth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RowWidth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PatternRepeats)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PatternRepeats)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrganicMatter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganicMatter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BicarbP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BicarbP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Potassium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Potassium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Magnesium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Magnesium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Calcium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Calcium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PHsoil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PHsoil)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PHbuffer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PHbuffer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cec)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cec)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationK)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationMg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationMg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationCa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationCa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Farm)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Farm.ProvinceCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Variety)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Variety.VarietyId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlotId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AFSOEC/AFSOEC/Views/AFSPlot/Details.cshtml
@model AFSOEC.Models.Plot

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Plot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DatePlanted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePlanted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateHarvested)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateHarvested)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantingRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantingRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantingRateByPounds)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantingRateByPounds)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RowWidth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RowWidth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PatternRepeats)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PatternRepeats)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrganicMatter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganicMatter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BicarbP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BicarbP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Potassium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Potassium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Magnesium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Magnesium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Calcium)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Calcium)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PHsoil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PHsoil)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PHbuffer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PHbuffer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cec)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cec)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationK)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationK)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationMg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationMg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationCa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationCa)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PercentBaseSaturationH)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PercentBaseSaturationH)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Farm)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Farm.ProvinceCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Variety)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Variety.VarietyId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PlotId" class="btn-lg btn-primary">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AFSOEC/AFSOEC/Views/AFSPlot/Index.cshtml
@model IEnumerable<AFSOEC.Models.Plot>
@using Microsoft.AspNetCore.Http


@{
    var heading = "Plot listing";
    if (Context.Session.GetString("criteria") == "crop")
    {
        heading += $" for crop: {Context.Session.GetString("CropName")}";
    }
    else if (Context.Session.GetString("criteria") == "variety")
    {
        heading += $" for variety: {Context.Session.GetString("VarietyName")}";
    }
    ViewData["Title"] = heading;
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-route-sortby="farm">Farm @Html.DisplayNameFor(model => model.Farm.Name)</a>
            </th>
            <th>
                Crop @Html.DisplayNameFor(model => model.Variety.Crop.Name)
            </th>
            <th>
                <a asp-route-sortby="variety">Variety @Html.DisplayNameFor(model => model.Variety.Name)</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePlanted)
            </th>
            <th>
                <a asp-route-sortby="cec">@Html.DisplayNameFor(model => model.Cec)</a>
            </th>

            <th>@Html.DisplayNameFor(model => model.Treatment)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Farm.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Variety.Crop.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Variety.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePlanted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cec)
            </td>
            <td>
                @foreach (var treatment in item.Treatment.Select(t => t.Name))
                {@treatment<br />}
            </td>
            <td>
                <a asp-controller="AFSTreatment" asp-action="Index" asp-route-PlotId="@item.PlotId" asp-route-FarmId="@item.FarmId">Manage Treatments</a> |
                <a asp-action="Edit" asp-route-id="@item.PlotId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PlotId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PlotId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>