AFSOEC/AFSOEC/Controllers/AFSPlotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AFSOEC.Models;
using Microsoft.AspNetCore.Http;

namespace AFSOEC.Controllers
{
    public class AFSPlotController : Controller
    {
        private readonly OECContext _context;

        // Constants
        // criteria identifiers for session variable
        const string CRITERIA_CROP = "crop";
        const string CRITERIA_VARIETY = "variety";
        const string CRITERIA_PLOT = "plot";

        public AFSPlotController(OECContext context)
        {
            _context = context;
        }

        // GET: AFSPlot
        public async Task<IActionResult> Index(int CropId, string CropName, int VarietyId, string VarietyName, string sortby, int PlotId, string FarmName)
        {
            var oECContext = _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .ThenInclude(v => v.Crop)
                .Include(p => p.Treatment)
                .AsQueryable();

            // check if a criteria has been persisted
            var criteria = HttpContext.Session.GetString("criteria");
           

        // check if a cropId or varietyId is passed and persist it along with a criteria identifier
            if (CropId != 0 || VarietyId != 0)
            {
            if (CropId != 0)
            {
                HttpContext.Session.SetInt32(nameof(CropId), CropId);
                HttpContext.Session.SetString(nameof(CropName), CropName);
                criteria = CRITERIA_CROP;
            }
            else
            {
                HttpContext.Session.SetInt32(nameof(VarietyId), VarietyId);
                HttpContext.Session.SetString(nameof(VarietyName), VarietyName);
                criteria = CRITERIA_VARIETY;
            }

           // HttpContext.Session.SetString(nameof(criteria), criteria);
            }
            else if (PlotId != 0)
            {
                HttpContext.Session.SetInt32(nameof(PlotId), PlotId);
                HttpContext.Session.SetString(nameof(FarmName), FarmName);
                criteria = CRITERIA_PLOT;

            }
            HttpContext.Session.SetString(nameof(criteria), criteria);


            // restrict the listing to plots with persisted criteria
            switch (criteria)
            {
                case CRITERIA_CROP:

                    oECContext = oECContext
                        .Where(p => p.Variety.CropId == HttpContext.Session.GetInt32(nameof(CropId)));
                    break;
                case CRITERIA_VARIETY:
                    oECContext = oECContext
                        .Where(p => p.VarietyId == (int)HttpContext.Session.GetInt32(nameof(VarietyId)));
                    break;
                case CRITERIA_PLOT:
                    oECContext = oECContext
                        .Where(p => p.PlotId == HttpContext.Session.GetInt32(nameof(PlotId)));
                    break;
                default:
                    oECContext = _context.Plot;
                    break;
            }

            // order the listing by selected column heading
            switch (sortby)
            {
                case "farm":
                    oECContext = oECContext.OrderBy(p => p.Farm.Name).ThenByDescending(p => p.DatePlanted);
                    break;
                case "variety":
                    oECContext = oECContext.OrderBy(p => p.Variety.Name).ThenByDescending(p => p.DatePlanted);
                    break;
                case "cec":
                    oECContext = oECContext.OrderBy(p => p.Cec).ThenByDescending(p => p.DatePlanted);
                    break;
                default:
                    oECContext = oECContext.OrderByDescending(p => p.DatePlanted);
                    break;
            }

            return View(await oECContext.ToListAsync());

        }

        // GET: AFSPlot/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .FirstOrDefaultAsync(m => m.PlotId == id);
            if (plot == null)
            {
                return NotFound();
            }

            return View(plot);
        }

        // GET: AFSPlot/Create
        public IActionResult Create()
        {
            var varietyList = new SelectList(_context.Variety.OrderBy(v => v.Name), "VarietyId", "Name");

            if (HttpContext.Session.GetString("criteria") == CRITERIA_CROP)
                // if the filter criteria was cropId, filter the drop-down to just varieties of that crop
                varietyList = new SelectList(_context.Variety.Where(v => v.CropId == (int)HttpContext.Session.GetInt32("cropId")).OrderBy(v => v.Name), "VarietyId", "Name");
            else
                // if the filter criteria was varietyId, default the drop-down to that value
                varietyList = new SelectList(_context.Variety.OrderBy(v => v.Name), "VarietyId", "Name", HttpContext.Session.GetInt32("varietyId"));

            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(f => f.Name), "FarmId", "Name");
            ViewData["VarietyId"] = varietyList;
            return View();
        }

        // POST: AFSPlot/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlotId,FarmId,VarietyId,DatePlanted,DateHarvested,PlantingRate,PlantingRateByPounds,RowWidth,PatternRepeats,OrganicMatter,BicarbP,Potassium,Magnesium,Calcium,PHsoil,PHbuffer,Cec,PercentBaseSaturationK,PercentBaseSaturationMg,PercentBaseSaturationCa,PercentBaseSaturationH,Comments")] Plot plot)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(f => f.Name), "FarmId", "Name", plot.FarmId);

            if (HttpContext.Session.GetString("criteria") == CRITERIA_CROP)
                // if the filter criteria was cropId, filter the drop-down to just varieties of that crop
                ViewData["VarietyId"] = new SelectList(_context.Variety.Where(v => v.CropId == (int)HttpContext.Session.GetInt32("CropId")).OrderBy(v => v.Name), "VarietyId", "Name", plot.VarietyId);
            else
                ViewData["VarietyId"] = new SelectList(_context.Variety.OrderBy(v => v.Name), "VarietyId", "Name", plot.VarietyId);
            return View(plot);
        }

        // GET: AFSPlot/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.Plot.FindAsync(id);
            if (plot == null)
            {
                return NotFound();
            }
            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(f => f.Name), "FarmId", "Name", plot.FarmId);
            ViewData["VarietyId"] = new SelectList(_context.Variety.OrderBy(v => v.Name), "VarietyId", "Name", plot.VarietyId);
            return View(plot);
        }

        // POST: AFSPlot/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlotId,FarmId,VarietyId,DatePlanted,DateHarvested,PlantingRate,PlantingRateByPounds,RowWidth,PatternRepeats,OrganicMatter,BicarbP,Potassium,Magnesium,Calcium,PHsoil,PHbuffer,Cec,PercentBaseSaturationK,PercentBaseSaturationMg,PercentBaseSaturationCa,PercentBaseSaturationH,Comments")] Plot plot)
        {
            if (id != plot.PlotId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlotExists(plot.PlotId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FarmId"] = new SelectList(_context.Farm.OrderBy(f => f.Name), "FarmId", "Name", plot.FarmId);
            ViewData["VarietyId"] = new SelectList(_context.Variety.OrderBy(v => v.Name), "VarietyId", "Name", plot.VarietyId);
            return View(plot);
        }

        // GET: AFSPlot/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .FirstOrDefaultAsync(m => m.PlotId == id);
            if (plot == null)
            {
                return NotFound();
            }

            return View(plot);
        }

        // POST: AFSPlot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

AFSOEC/AFSOEC/Controllers/AFSVarietyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AFSOEC.Models;
using Microsoft.AspNetCore.Http;

namespace AFSOEC.Controllers
{
    public class AFSVarietyController : Controller
    {
        private readonly OECContext _context;

        public AFSVarietyController(OECContext context)
        {
            _context = context;
        }

        // GET: AFSVariety
        public async Task<IActionResult> Index(int? CropId )
        {
            int currentCropId = 0;
            string currentCropName = "";

            //If there’s no cropId in the cookie or session variables either, return to 
            //the XXCrop controller with a message asking them to select a crop to see 
            //its varieties.
            //CropId is not coming from URL
            if (CropId == null)  
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SCropId")))  //CropId Exists in the session
                {
                    currentCropId = int.Parse(HttpContext.Session.GetString("SCropId"));
                    
                }
                else
                {
                    TempData["message"] = "Please select a crop..";
                    return RedirectToAction("Index", "AFSCrop");
                }
                   
            }
            //CropId coming from URL
            else
            {
                currentCropId = (int)CropId;
                //add session variable
                HttpContext.Session.SetString("SCropId", currentCropId.ToString());
                
            }

            currentCropName = _context.Variety
                            .Where(v => v.CropId == currentCropId)
                            .Select(v => v.Crop.Name)
                            .FirstOrDefault();

            HttpContext.Session.SetString("SCropName", currentCropName);

            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
           

            var AFSOECContext = _context.Variety
                .Where(v => v.CropId == currentCropId)
                .ToListAsync();
            return View(await AFSOECContext);
        }

        // GET: AFSVariety/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(v => v.Crop)
                .FirstOrDefaultAsync(m => m.VarietyId == id);
            if (variety == null)
            {
                return NotFound();
            }
            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View(variety);
        }

        // GET: AFSVariety/Create
        public IActionResult Create()
        {
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId");
            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View();
        }

        // POST: AFSVariety/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VarietyId,CropId,Name")] Variety variety)
        {
            if (ModelState.IsValid)
            {
                _context.Add(variety);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View(variety);
        }

        // GET: AFSVariety/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety.FindAsync(id);
            if (variety == null)
            {
                return NotFound();
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View(variety);
        }

        // POST: AFSVariety/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VarietyId,CropId,Name")] Variety variety)
        {
            if (id != variety.VarietyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(variety);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VarietyExists(variety.VarietyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View(variety);
        }

        // GET: AFSVariety/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(v => v.Crop)
                .FirstOrDefaultAsync(m => m.VarietyId == id);
            if (variety == null)
            {
                return NotFound();
            }

            //add Name from session to ViewBag objects
            ViewBag.Name = HttpContext.Session.GetString("SCropName");
            return View(variety);
        }

        // POST: AFSVariety/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var variety = await _context.Variety.FindAsync(id);
            _context.Variety.Remove(variety);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VarietyExists(int id)
        {
            return _context.Variety.Any(e => e.VarietyId == id);
        }
    }
}

AFSOEC/AFSOEC/Views/AFSCrop/Create.cshtml
@model AFSOEC.Models.Crop

@{
    ViewData["Title"] = "Create Crop";
}

<h2 style="color:forestgreen">Create Crop</h2>

<h4>Crop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn-lg btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AFSOEC/AFSOEC/Views/AFSCrop/Delete.cshtml
@model AFSOEC.Models.Crop

@{
    ViewData["Title"] = "Delete Crop";
}

<h2>Delete Crop</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Crop</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CropId" />
        <input type="submit" value="Delete" class="btn-lg btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AFSOEC/AFSOEC/Views/AFSCrop/Details.cshtml
 @model AFSOEC.Models.Crop

@{
    ViewData["Title"] = "Crop Details";
}

<h2>Crop Details</h2>

<div>
    <h4>Crop</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    <a class="btn-lg btn-primary" asp-action="Edit" asp-route-id="@Model.CropId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AFSOEC/AFSOEC/Views/AFSCrop/Edit.cshtml
@model AFSOEC.Models.Crop

@{
    ViewData["Title"] = "Edit Crop";
}

<h2>Edit Crop</h2>

<h4>Crop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="CropId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>  
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AFSOEC/AFSOEC/Views/AFSCrop/Index.cshtml
@model IEnumerable<AFSOEC.Models.Crop>

@{
    ViewData["Title"] = "Crop Listing";
}

<h2>Crop Listing</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-controller="AFSVariety" asp-action="Index" asp-route-CropId="@item.CropId" asp-route-Name="@item.Name">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CropId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CropId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CropId">Delete</a> |
                <a asp-controller="AFSPlot" asp-action="Index" asp-route-CropId="@item.CropId" asp-route-CropName="@item.Name">Show Plots</a>
            </td>
        </tr>
}   
    </tbody>
</table>